# Generated by Django 4.0.1 on 2022-02-01 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_city_note_webpage_alter_person_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='notes',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.note'),
        ),
        migrations.AlterField(
            model_name='person',
            name='place',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='person.place'),
        ),
        migrations.AlterField(
            model_name='person',
            name='webpage',
            field=models.ManyToManyField(blank=True, null=True, to='person.Webpage'),
        ),
    ]
