# Generated by Django 4.0.1 on 2022-02-01 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_alter_person_notes_alter_person_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='place',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='people', to='person.place'),
        ),
        migrations.AlterField(
            model_name='place',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='places', to='person.city'),
        ),
    ]
