# Generated by Django 4.0.1 on 2022-02-01 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_remove_person_webpage_person_webpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='webpage',
        ),
        migrations.AddField(
            model_name='webpage',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='person.person'),
        ),
    ]
