# Generated by Django 4.0.1 on 2022-02-01 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0008_remove_person_webpage_webpage_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webpage',
            name='person',
        ),
        migrations.AddField(
            model_name='person',
            name='webpage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.webpage'),
        ),
    ]
