# Generated by Django 4.0.1 on 2022-02-01 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0009_remove_webpage_person_person_webpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='person',
            name='place',
        ),
        migrations.RemoveField(
            model_name='person',
            name='webpage',
        ),
        migrations.AddField(
            model_name='note',
            name='person',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.person'),
        ),
        migrations.AddField(
            model_name='place',
            name='person',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='places', to='person.person'),
        ),
        migrations.AddField(
            model_name='webpage',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.person'),
        ),
    ]
