# Generated by Django 4.0.1 on 2022-02-01 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0011_alter_webpage_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='websites', to='person.person'),
        ),
    ]
