# Generated by Django 4.0.1 on 2022-02-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0012_alter_webpage_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='created',
            field=models.DateField(auto_now=True),
        ),
    ]
