# Generated by Django 4.0.1 on 2022-02-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0013_note_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='telephone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
