# Generated by Django 4.0.1 on 2022-02-02 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0014_person_email_person_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='person',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='person.person'),
        ),
    ]
