# Generated by Django 4.0.1 on 2022-02-03 09:14

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0015_alter_note_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default=None, force_format=None, keep_meta=True, null=True, quality=85, size=[500, 300], upload_to='images/%Y/%m/%d/'),
        ),
    ]
