# Generated by Django 4.0.1 on 2022-02-09 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0016_alter_person_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('fuel', models.CharField(max_length=3)),
                ('year', models.CharField(max_length=9)),
                ('plate', models.CharField(max_length=10)),
                ('owner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='person.person')),
            ],
        ),
    ]
