# Generated by Django 4.0.1 on 2022-02-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0017_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='person',
        ),
        migrations.AddField(
            model_name='place',
            name='persons',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='places', to='person.Person'),
        ),
    ]
