# Generated by Django 4.0.1 on 2022-02-09 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0018_remove_place_person_place_persons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='persons',
            new_name='person',
        ),
    ]
