# Generated by Django 4.0.1 on 2022-02-09 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0019_rename_persons_place_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='person',
            new_name='persons',
        ),
    ]
